version: '3.3'
services:
  web:
    image: tubes-1:latest
    # build: .
    volumes:
      - "./:/usr/src/binotify"
      - "./assets/music:/usr/src/binotify/public_html/music"
      - "./assets/image:/usr/src/binotify/public_html/image"
      - "./php.ini:/usr/local/etc/php/php.ini-production"
    ports:
      - "8008:80"
  db:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - "./database:/docker-entrypoint-initdb.d"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8001:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306